### ISSUE TITLE
Add support for progress callbacks

### ISSUE THREAD

**Issue by Acconut** [transloadit/java-sdk#10]
A possible future addition to the SDK would be to get updates about the progress of the current file uploads, which are useful to show the user that there is some background activity going on. This can be achieved by adding a ProgressCallback interface which can then be attached to an Assembly instance. This also allows to add future callbacks, such as onStartExecuting or onAssemblyFinish.

```java
public interface ProgressCallback {
    void onUploadProgress(int bytesExpected, int bytesReceived);
}
```

```java
Assembly assembly = transloadit.newAssembly();

assembly.addStep("encode", "/video/encode", new HashMap());
assembly.addFile(new File("LICENSE"));

assembly.addProgressCallback(new ProgressCallback() {
    public void onUploadProgress(int bytesExpected, int bytesReceived) {
        System.out.printf("Upload at %d%%\n", 100 * bytesReceived / bytesExpected);
    }
});

AssemblyResponse assemblyResponse = assembly.save();
// etc ...
```

What are your thoughts?

**Comment by ifedapoolarewaju** [comment]
this is now fixed with the AsyncAssembly feature in `v0.1.0`
