### ISSUE TITLE
Add support for aborting assembly upload

### ISSUE THREAD

**Issue by Acconut** [transloadit/java-sdk#11]
It would be convenient to be able to stop current uploads, for example for a user unintentionally selected the wrong file to upload. A possible interface for this could be designed as seen below. Notice how a second thread is spawned which then cancels the upload after a short timeout. This solves the issue that Assembly#save is a blocking call. However, implementing such a solution requires create care to ensure thread safety!

As a final consideration, we should discuss whether cancelling an upload should also cancel the assembly, by default, using the DELETE endpoint (https://transloadit.com/docs/api-docs/#cancel-an-assembly)

```java
Assembly assembly = transloadit.newAssembly();

assembly.addStep("encode", "/video/encode", new HashMap());
assembly.addFile(new File("LICENSE"));

Thread timeoutThread = new Thread(new Runnable() {
    public void run() {
         Thread.sleep(3 * 1000);
         assembly.abort(); // or maybe stopUpload
    }
});
timeoutThread.start();

AssemblyResponse assemblyResponse = assembly.save();
```

What are your thoughts?

**Comment by ifedapoolarewaju** [comment]
this is now fixed with the AsyncAssembly feature
