### ISSUE TITLE
Assembly notifications API

### ISSUE THREAD

**Issue by ifedapoolarewaju** [transloadit/java-sdk#13]
it'll be nice to have a method that retrieves assembly notifications. maybe a method named `getAssemblyNotifications` under the `Transloadit` class

**Comment by cdr-chakotay** [comment]
Honestly don't know if this is useful as we are getting all the assembly notifications with the socket or the SSE. Those notifications are more for the customer's server.

If we want to wait until the assembly finishes, we can do this already. No need for a webhook. 
What do you think @Acconut ?

**Comment by Acconut** [comment]
This issue can probably be closed. A few years back there was an API to list the notifications of an Assembly. This endpoint has been removed ~2 years ago and now information about the notifications are included in the Assembly status on its own, so this is not needed anymore.
