### ISSUE TITLE
ListResponse size

### ISSUE THREAD

**Issue by ifedapoolarewaju** [transloadit/java-sdk#14]
when a paginated json list is retrieved from the Transloadit API, with [listAssemblies](https://github.com/transloadit/java-sdk/blob/master/src/main/java/com/transloadit/sdk/Transloadit.java#L152) for example, the method [ListResponse.size](https://github.com/transloadit/java-sdk/blob/master/src/main/java/com/transloadit/sdk/response/ListResponse.java#L26) returns the total number of assemblies owned under the user account. The expected behavior is to return the number of assemblies present in that particular json response.

**Comment by Acconut** [comment]
Both numbers are important and may be used in different scenarios. If one is interested in "the number of assemblies present in that particular json response", they can also use `list.getItems().length()` at the moment.

**Comment by ifedapoolarewaju** [comment]
> Both numbers are important and may be used in different scenarios

Yes this was my thought also, but I think the intuitively, this name `list.size` might be misleading for the purpose it serves currently. The [documentation](https://github.com/transloadit/java-sdk/blob/master/src/main/java/com/transloadit/sdk/response/ListResponse.java#L24) as a matter of fact is misleading. I was thinking if `list.size` does the same as `list.getItems().length()`, since it is already documented to behave that way. Then a method `list.totalSize` or something could serve for what `list.size` currently does.

**Comment by Acconut** [comment]
IMO, there is no correct way for how `ListResponse#size()` should behave but in the ends it's up to each person own preferences. What you should still keep in mind is that such a change would be breaking backwards compatibility and even if the usage for the Java SDK is still low, I would like to avoid this.

**Comment by ifedapoolarewaju** [comment]
closing this based on Marius' comment
