### ISSUE TITLE
AsyncAssembly only works when there are File uploads

### ISSUE THREAD

**Issue by ifedapoolarewaju** [transloadit/java-sdk#22]
The AsyncAssembly listener seems not to be triggered whenever an Assembly is created without files to upload.

**Comment by tim-kos** [comment]
Any updates here, Ife?

**Comment by Acconut** [comment]
@ifedapoolarewaju Are there any updates?

**Comment by cdr-chakotay** [comment]
Will close this as I reimplemented asynchronous uploads.
