### ISSUE TITLE
Switch to GitHub Action and remove Bintray

### ISSUE THREAD

**Issue by Acconut** [transloadit/java-sdk#40]

**Comment by cdr-chakotay** [comment]
We could try out this GitHubAction-configuration as Travis-CI replacement.
It defines a build process with Gradle with an assemble step and a separate test run.
The used Java Versions are 8 and 11 (Adopt OpenJDK). Java 6 is not supported.
The build OS is ubuntu latest.
Currently not included: Slack integration

File:
[java_ci.yml.zip](https://github.com/transloadit/java-sdk/files/6310792/java_ci.yml.zip)

**Comment by Acconut** [comment]
The GitHub Actions configuration looks good! Please open a pull request (PR) for it, if you want.

Regarding the Slack integration, https://github.com/8398a7/action-slack seems to be a good choice. We are already using it in the Node.js SDK and can borrow the configuration from there: https://github.com/transloadit/node-sdk/blob/master/.github/workflows/master.yml#L66-L77

The only thing then needed is an automatic publication of the latest releases on the Maven Central Repository. The process is described in https://docs.github.com/en/actions/guides/publishing-java-packages-with-maven#publishing-packages-to-the-maven-central-repository, but this can be done is a second PR. Not need to do all of that at the same time. I can also take care of this Maven publication since I should have the credentials. 

Just as a bit of context: The Travis CI script does not include the Maven part because we used Bintray instead, which then published the package to Maven. However, Bintray is shutting down, so we have to take care of the Maven publication on our own.

**Comment by cdr-chakotay** [comment]
I' d prefer doing this in separate PRs. We can have a talk about the maven integration.

**Comment by cdr-chakotay** [comment]
Regarding the Maven integration:
We should also address this error:
```
The maven plugin has been deprecated. This is scheduled to be removed in Gradle 7.0. 
Please use the maven-publish plugin instead. Consult the upgrading guide for further information: 
```
[https://docs.gradle.org/6.8.3/userguide/upgrading_version_5.html#legacy_publication_system_is_deprecated_and_replaced_with_the_publish_plugins](https://docs.gradle.org/6.8.3/userguide/upgrading_version_5.html#legacy_publication_system_is_deprecated_and_replaced_with_the_publish_plugins)

**Comment by cdr-chakotay** [comment]
We also need the Webhook secret for the actions. I've seen you are already on it.

In my opinion maven-publish works correctly

**Comment by Acconut** [comment]
Here is the article describing publishing with Gradle: https://docs.github.com/en/actions/guides/publishing-java-packages-with-gradle
