### ISSUE TITLE
Update GitHub Releases

### ISSUE THREAD

**Issue by cdr-chakotay** [transloadit/java-sdk#43]
The latest Release we have on GitHub is 0.1.5 versus 0.1.6 on [Bintray](https://bintray.com/package/files/transloadit/maven/transloadit?order=asc&sort=name&basePath=com%2Ftransloadit%2Fsdk%2Ftransloadit%2F0.1.6&tab=files).

Maven search still lists only [0.1.5 ](https://repo1.maven.org/maven2/com/transloadit/sdk/transloadit/)

Maybe we should release 0.1.6 also on GitHub and Maven in order to evade future conflicts with
an automated Github Action for releases (as planned).

**Comment by Acconut** [comment]
Good idea! We can take care of this once the Maven integration works, so the Github release will automatically push to Maven as well.
