### ISSUE TITLE
Add Java code style linter

### ISSUE THREAD

**Issue by Acconut** [transloadit/java-sdk#44]
Now that we have Github Actions setup, it would be nice if it could also run a code linter on every commits to warn us about common mistakes and keep the code style consistent (indentation, spaces, unused variables etc). A common tool for this task seems to be super-linter (https://github.com/github/super-linter), which also supports Java.

**Comment by cdr-chakotay** [comment]
I will have a peek on that. I guess we want it to check every commit and not only PRs to the Master branch?

**Comment by Acconut** [comment]
Exactly! I think it would be best to have this as a separate job next to the Gradle step, so that both jobs, the linting and the tests, are always run even if one of them fails.
