### ISSUE TITLE
Implement retries for HTTP requests

### ISSUE THREAD

**Issue by Acconut** [transloadit/java-sdk#56]
Currently, the Java SDK does not retry requests. There are two cases in which automatic retries (i.e. without the SDK user's interaction) would be helpful:

* if the HTTP request is not able to be completed because of a connection issue (tus already handles this for the uploads) but there are also other HTTP requests which could fail
* if the network connection is stable but the server is rejecting the request because the per-customer rate limit is hit (here, a delay should be applied before retrying, see exponential back-off algorithms)

**Comment by cdr-chakotay** [comment]
Implemented with release 0.2.0
