### ISSUE TITLE
Update Documentation

### ISSUE THREAD

**Issue by cdr-chakotay** [transloadit/java-sdk#58]
- [https://transloadit.com/docs/#sdks](https://transloadit.com/docs/#sdks) still lists the Travis CI badge. As we have removed Travis CI we should replace it with the most recent one.

- [https://transloadit.com/docs/#java-sdk](https://transloadit.com/docs/#java-sdk) links to Bintray and advertises the jcenter repository. They are unavailable/discontinued. We should only keep the maven central reference.

**Comment by Acconut** [comment]
Good point! The content available at https://transloadit.com/docs/#java-sdk is just the README.md file from the SDKs imported into our website. So basically, we update the information in the README.md and then ask @kvz to import in into the website.

**Comment by cdr-chakotay** [comment]
I'll have a look at this

**Comment by cdr-chakotay** [comment]
@kvz can you import the content of the updated readme to the website ? I made some minor changes regarding availability of the releases

**Comment by kvz** [comment]
Done :ok_hand:
