### ISSUE TITLE
Use of UploadProgressListener causes exception

### ISSUE THREAD

**Issue by cdr-chakotay** [transloadit/java-sdk#69]
The use of the UploadProgressListener of the Async Assemblies causes an NullPointerException as the AssemblyRunnable calls ```getListener().onAssemblyFinished(watchStatus());``` . 
If you use the UploadProgressListener there is no AssemblyProgressListener instance that can be returned by ```getListener()```.  In this case, you are facing a NullPointerException every time the assembly processing is finished.

This behavior is also reproducible with the examples provided by the SDK.

**Comment by Acconut** [comment]
Oh, good finding! Does this mean that the UploadProgressListener is not usable because it always leads to an exception?

**Comment by cdr-chakotay** [comment]
Yeah, at this point you cannot use it without exception. I think it was meant to replace the AssemblyProgressListener as AsyncAssembly instantiation with an AssemblyProgressListener is deprecated.

We should have a look at what we prefer, I mean it is all done twice with both listeners.

**Comment by Acconut** [comment]
> We should have a look at what we prefer, I mean it is all done twice with both listeners.

We should definitely fix the UploadProgressListener. But for the sake of backwards compatibility, we have to keep both listener interfaces unless we do a major release, which I would like to avoid doing.

**Comment by cdr-chakotay** [comment]
> > We should have a look at what we prefer, I mean it is all done twice with both listeners.
> 
> We should definitely fix the UploadProgressListener. But for the sake of backwards compatibility, we have to keep both listener interfaces unless we do a major release, which I would like to avoid doing.

I think I can fix this quick and dirty with a null check for example. Or we extend the capabilities of the upload progress listener.
